import * as fs from 'fs';
import chalk from 'chalk';

export interface EnvDiff {
  missingInExample: string[];
  missingInEnv: string[];
  commonVariables: string[];
}

export function diffEnvFiles(envFile: string, exampleFile: string): EnvDiff {
  const envVars = parseEnvFile(envFile);
  const exampleVars = parseEnvFile(exampleFile);

  const envKeys = new Set(Object.keys(envVars));
  const exampleKeys = new Set(Object.keys(exampleVars));

  const missingInExample: string[] = [];
  const missingInEnv: string[] = [];
  const commonVariables: string[] = [];

  // Find variables in .env but not in .env.example
  envKeys.forEach((key) => {
    if (!exampleKeys.has(key)) {
      missingInExample.push(key);
    } else {
      commonVariables.push(key);
    }
  });

  // Find variables in .env.example but not in .env
  exampleKeys.forEach((key) => {
    if (!envKeys.has(key)) {
      missingInEnv.push(key);
    }
  });

  return {
    missingInExample: missingInExample.sort(),
    missingInEnv: missingInEnv.sort(),
    commonVariables: commonVariables.sort(),
  };
}

function parseEnvFile(filePath: string): Record<string, string> {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const vars: Record<string, string> = {};

  lines.forEach((line) => {
    const trimmed = line.trim();

    // Skip empty lines and comments
    if (trimmed === '' || trimmed.startsWith('#')) {
      return;
    }

    // Parse key=value
    const equalIndex = trimmed.indexOf('=');
    if (equalIndex > 0) {
      const key = trimmed.substring(0, equalIndex).trim();
      const value = trimmed.substring(equalIndex + 1).trim();
      vars[key] = value;
    }
  });

  return vars;
}

export function displayDiff(diff: EnvDiff, envFile: string, exampleFile: string): void {
  console.log(chalk.blue.bold('\n📊 Environment Diff Report\n'));
  console.log(chalk.gray(`Comparing: ${envFile} ↔ ${exampleFile}\n`));

  // Common variables
  if (diff.commonVariables.length > 0) {
    console.log(chalk.green(`✓ ${diff.commonVariables.length} variable(s) in both files`));
  }

  // Missing in .env
  if (diff.missingInEnv.length > 0) {
    console.log(chalk.yellow(`\n⚠️  ${diff.missingInEnv.length} variable(s) in ${exampleFile} but NOT in ${envFile}:`));
    diff.missingInEnv.forEach((key) => {
      console.log(chalk.yellow(`  • ${key}`));
    });
    console.log(chalk.gray('  → You may need to add these to your .env file'));
  }

  // Missing in .env.example
  if (diff.missingInExample.length > 0) {
    console.log(chalk.cyan(`\n💡 ${diff.missingInExample.length} variable(s) in ${envFile} but NOT in ${exampleFile}:`));
    diff.missingInExample.forEach((key) => {
      console.log(chalk.cyan(`  • ${key}`));
    });
    console.log(chalk.gray('  → Consider adding these to .env.example for documentation'));
  }

  // Summary
  if (diff.missingInEnv.length === 0 && diff.missingInExample.length === 0) {
    console.log(chalk.green('\n✓ Files are in sync!'));
  } else {
    console.log(chalk.yellow('\n⚠️  Files are out of sync'));
  }

  console.log();
}

export function generateMissingVars(diff: EnvDiff, outputFile: string): void {
  if (diff.missingInEnv.length === 0) {
    return;
  }

  let content = `# Missing variables from .env.example\n`;
  content += `# Generated by EnvGuard\n\n`;

  diff.missingInEnv.forEach((key) => {
    content += `${key}=\n`;
  });

  fs.writeFileSync(outputFile, content, 'utf-8');
  console.log(chalk.green(`\n✓ Generated ${outputFile} with missing variables`));
  console.log(chalk.gray(`  Fill in the values and merge into your .env file`));
}
